import pygame
from . import tiles_logic

# Define images for tiles
p1_img = pygame.image.load('img/1p.png').convert_alpha()
p2_img = pygame.image.load('img/2p.png').convert_alpha()
p3_img = pygame.image.load('img/3p.png').convert_alpha()
p4_img = pygame.image.load('img/4p.png').convert_alpha()
p5_img = pygame.image.load('img/5p.png').convert_alpha()
p6_img = pygame.image.load('img/6p.png').convert_alpha()
p7_img = pygame.image.load('img/7p.png').convert_alpha()
p8_img = pygame.image.load('img/8p.png').convert_alpha()
p9_img = pygame.image.load('img/9p.png').convert_alpha()
m1_img = pygame.image.load('img/1m.png').convert_alpha()
m2_img = pygame.image.load('img/2m.png').convert_alpha()
m3_img = pygame.image.load('img/3m.png').convert_alpha()
m4_img = pygame.image.load('img/4m.png').convert_alpha()
m5_img = pygame.image.load('img/5m.png').convert_alpha()
m6_img = pygame.image.load('img/6m.png').convert_alpha()
m7_img = pygame.image.load('img/7m.png').convert_alpha()
m8_img = pygame.image.load('img/8m.png').convert_alpha()
m9_img = pygame.image.load('img/9m.png').convert_alpha()
s1_img = pygame.image.load('img/1s.png').convert_alpha()
s2_img = pygame.image.load('img/2s.png').convert_alpha()
s3_img = pygame.image.load('img/3s.png').convert_alpha()
s4_img = pygame.image.load('img/4s.png').convert_alpha()
s5_img = pygame.image.load('img/5s.png').convert_alpha()
s6_img = pygame.image.load('img/6s.png').convert_alpha()
s7_img = pygame.image.load('img/7s.png').convert_alpha()
s8_img = pygame.image.load('img/8s.png').convert_alpha()
s9_img = pygame.image.load('img/9s.png').convert_alpha()
c_img = pygame.image.load('img/c.png').convert_alpha()
h_img = pygame.image.load('img/h.png').convert_alpha()
ha_img = pygame.image.load('img/ha.png').convert_alpha()
hi_img = pygame.image.load('img/hi.png').convert_alpha()
ni_img = pygame.image.load('img/ni.png').convert_alpha()
ki_img = pygame.image.load('img/ki.png').convert_alpha()
mi_img = pygame.image.load('img/mi.png').convert_alpha()

# Define tile objects
p1 = tiles_logic.Tile('p', 1, p1_img)
p2 = tiles_logic.Tile('p', 2, p2_img)
p3 = tiles_logic.Tile('p', 3, p3_img)
p4 = tiles_logic.Tile('p', 4, p4_img)
p5 = tiles_logic.Tile('p', 5, p5_img)
p6 = tiles_logic.Tile('p', 6, p6_img)
p7 = tiles_logic.Tile('p', 7, p7_img)
p8 = tiles_logic.Tile('p', 8, p8_img)
p9 = tiles_logic.Tile('p', 9, p9_img)
m1 = tiles_logic.Tile('m', 1, m1_img)
m2 = tiles_logic.Tile('m', 2, m2_img)
m3 = tiles_logic.Tile('m', 3, m3_img)
m4 = tiles_logic.Tile('m', 4, m4_img)
m5 = tiles_logic.Tile('m', 5, m5_img)
m6 = tiles_logic.Tile('m', 6, m6_img)
m7 = tiles_logic.Tile('m', 7, m7_img)
m8 = tiles_logic.Tile('m', 8, m8_img)
m9 = tiles_logic.Tile('m', 9, m9_img)
s1 = tiles_logic.Tile('s', 1, s1_img)
s2 = tiles_logic.Tile('s', 2, s2_img)
s3 = tiles_logic.Tile('s', 3, s3_img)
s4 = tiles_logic.Tile('s', 4, s4_img)
s5 = tiles_logic.Tile('s', 5, s5_img)
s6 = tiles_logic.Tile('s', 6, s6_img)
s7 = tiles_logic.Tile('s', 7, s7_img)
s8 = tiles_logic.Tile('s', 8, s8_img)
s9 = tiles_logic.Tile('s', 9, s9_img)
c = tiles_logic.Tile('z_c', 10, c_img)
ha = tiles_logic.Tile('z_ha', 11, ha_img)
h = tiles_logic.Tile('z_h', 12, h_img)
mi = tiles_logic.Tile('z_mi', 13, mi_img)
hi = tiles_logic.Tile('z_hi', 14, hi_img)
ni = tiles_logic.Tile('z_ni', 15, ni_img)
ki = tiles_logic.Tile('z_ki', 16, ki_img)

# Create wall
wall = [p1, p2, p3, p4, p5, p6, p7, p8, p9, m1, m2, m3, m4, m5, m6,  m7, m8, m9, s1, s2, s3, s4, s5, s6, s7, s8, s9, c, ha, h, mi, hi, ni, ki, p1, p2, p3, p4, p5, p6, p7, p8, p9, m1, m2, m3, m4, m5, m6,  m7, m8, m9, s1, s2, s3, s4, s5, s6, s7, s8, s9, c, ha, h, mi, hi, ni, ki, p1, p2, p3, p4, p5, p6, p7, p8, p9, m1, m2, m3, m4, m5, m6,  m7, m8, m9, s1, s2, s3, s4, s5, s6, s7, s8, s9, c, ha, h, mi, hi, ni, ki, p1, p2, p3, p4, p5, p6, p7, p8, p9, m1, m2, m3, m4, m5, m6,  m7, m8, m9, s1, s2, s3, s4, s5, s6, s7, s8, s9, c, ha, h, mi, hi, ni, ki]
